server:
  port: ${PORT:8098}

# configure eureka client
#eureka:
#  instance:
#    leaseRenewalIntervalInSeconds: 1
#    leaseExpirationDurationInSeconds: 3
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:1111/eureka/

# custom attribute for the actuator info endpoint
info:
  app:
    name: WEB-SERVICE

# give the application a name
spring:
  application:
    name: WEB-SERVICE

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

