spring:
  application:
    name: web-ui-service
server:
  port: 0
eureka:
  instance:
    appname: web-ui-service
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    fetch-registry: true

ribbon:
  http:
    client:
      enabled: true
